## This is a sample build configuration for Java (Maven).
## Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
## Only use spaces to indent your .yml configuration.
## -----
## You can specify a custom docker image from Docker Hub as your build environment.
## image: maven:3.6.1

## pipelines:
##   default:
##     - step:
##         caches:
##           - maven
##         script: # Modify the commands below to build your repository.
##           - git clone https://giscardti:Giscard!10@bitbucket.org/netlit-team/logging.git
##           - cd logging
##           - mvn clean install -B -Dmaven.javadoc.skip=true verify
##           - cd ..
##           - mvn clean package -B -DskipTests=true -Dmaven.javadoc.skip=true verify
##        services:
##           - docker          
##     - pipe: atlassian/aws-ecs-deploy:0.3.0
##         variables:
##           AWS_ACCESS_KEY_ID: 'AKIAW6XF2QZI56OHM2MH'
##           AWS_SECRET_ACCESS_KEY: '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'
##           AWS_DEFAULT_REGION: 'us-east-2'
##           ECS_CLUSTER_NAME: 'netlit-cluster'
##           ECS_SERVICE_NAME: 'accounts'
##           ECS_TASK_DEFINITION: 'accounts-app-task:17'
##           DEBUG: 'true' # Optional