package br.com.netlit.accounts.domain.account.general.entity;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import br.com.netlit.accounts.domain.account.general.resource.SchoolGradeRoomRequest;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "SchoolGradeRoom")
public class SchoolGradeRoomEntity {

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	private UUID id;
	@DynamoDBAttribute(attributeName = "Name")
	private String name;
	@DynamoDBAttribute(attributeName = "Code")
	private String code;
	@DynamoDBAttribute(attributeName = "SubAccountId")
	private UUID subAccountId;

	public static SchoolGradeRoomEntity valueOf(SchoolGradeRoomRequest request) {
		
		return SchoolGradeRoomEntity
			.builder()
			.id(request.getId())
			.name(request.getName())
			.code(request.getCode())
			.subAccountId(request.getSubAccountId())
			.build();
		
	}
}
