package br.com.netlit.accounts.domain.account.general.entity;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "SchoolRoomStudent")
public class SchoolRoomStudentEntity {

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	private UUID id;
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "SchoolGradeRoomId")
	private UUID schoolGradeRoomId;
	@DynamoDBAttribute(attributeName = "SubAccountId")
	private UUID subAccountId;
}
