package br.com.netlit.accounts.domain.account.general.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.persistence.OrderBy;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import br.com.netlit.accounts.infra.database.LocalDateConverter;
import br.com.netlit.accounts.infra.database.LocalDateTimeConverter;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "SubAccount")
public class SubAccountEntity {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "Id")
  private UUID id;
  @DynamoDBAttribute(attributeName = "AccountId")
  private UUID accountId;
  @DynamoDBAttribute(attributeName = "Name")
  private String name;
  @DynamoDBAttribute(attributeName = "BirthDate")
  @DynamoDBTypeConverted(converter = LocalDateConverter.class)
  private LocalDate birthDate;
  @DynamoDBTypeConvertedEnum
  @DynamoDBAttribute(attributeName = "Gender")
  private Gender gender;
  @DynamoDBAttribute(attributeName = "LastName")
  private String lastName;
  @DynamoDBTypeConvertedEnum
  @DynamoDBAttribute(attributeName = "Type")
  private AccountType type;
  @DynamoDBAttribute(attributeName = "School")
  private SchoolEntity school;
  
  @OrderBy("ASC")
  @DynamoDBAttribute(attributeName = "Created")
  @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
  private LocalDateTime created;
  
  
}
